# A매장 설정
store:
  id: "A"
  name: "동탄점"
  website_url: "http://members.iparking.co.kr/#!"
  
login:
  username: "dtctrit2704"
  password: "dtctrit2704"

# 쿠폰 설정 - 시간 독립적 설계 (4_discount_logic.mdc 기반)
coupons:
  FREE_COUPON:
    name: "30분할인권(무료)"
    type: "FREE"
    duration_minutes: 60
    priority: 0
  PAID_COUPON:
    name: "1시간할인권(유료)"
    type: "PAID"
    duration_minutes: 60
    priority: 1
  WEEKEND_COUPON:
    name: "1시간주말할인권(유료)"
    type: "WEEKEND"
    duration_minutes: 60
    priority: 2

# 할인 정책 - 시간 기반 (분 단위)
discount_policy:
  weekday:
    target_hours: 3
    max_coupons: 5
  weekend:
    target_hours: 2
    max_coupons: 3

# 웹 셀렉터
selectors:
  # 로그인 관련
  login:
    username_input: "#id"
    password_input: "#password"
    login_button: "#login"
    car_number_input: "#carNumber"
  
  # 팝업 처리
  popups:
    intro_skip: "#skip"
    notice_cancel: "#popupCancel"
    after_login_home: "#gohome"
    after_login_start: "#start"
    popup_ok: "#popupOk"
  
  # 차량 검색
  search:
    car_number_input: "#carNumber"
    search_button: 'button[name="search"]'
    search_button_alt1: ".btn-search"
    search_button_alt2: 'button:has-text("검색")'
    next_button: "#next"
    next_button_alt: 'button:has-text("차량 선택")'
    park_name: "#parkName"
    no_result_text: 'text="검색된 차량이 없습니다"'
  
  # 쿠폰 관련
  coupons:
    product_list: "#productList"
    product_rows: "#productList tr"
    empty_message: "#productList td.empty"
    my_dc_list: "#myDcList"
    my_dc_rows: "#myDcList tr"
    all_dc_list: "#allDcList"
    all_dc_rows: "#allDcList tr"
    apply_button: 'button:has-text("적용")'
    apply_button_prefix: "#apply_"
    
    # 할인내역 테이블 셀렉터 (공통 쿠폰 계산기용)
    # A 매장 특징: ID 기반 테이블 식별
    discount_selectors:
      - "#myDcList tr"          # 우리 매장 할인 내역
      - "#allDcList tr"         # 전체 할인 내역
      - "tbody#myDcList tr"     # tbody를 명시한 우리 매장 할인 내역
      - "tbody#allDcList tr"    # tbody를 명시한 전체 할인 내역
    
    # 쿠폰 이름 → 키 매핑 (공통 쿠폰 계산기용)
    coupon_key_mapping:
      "30분할인권(무료)": "FREE_COUPON"
      "1시간할인권(유료)": "PAID_COUPON"
      "1시간주말할인권(유료)": "WEEKEND_COUPON"
    
    # A 매장 테이블 데이터 구조 정보
    table_structure:
      description: "날짜 | 할인권명 | 수량"
      coupon_name_cell_index: 2  # 쿠폰명이 있는 셀 인덱스 (0부터 시작)
      quantity_cell_index: 3     # 수량이 있는 셀 인덱스
      has_my_history: true       # A 매장은 my_history와 total_history 구분
      example: "2025-08-16 | 30분할인권(무료) | 1매"

# 차량 검색 실패 감지 설정
search_failure_detection:
  # 우선순위 순으로 시도할 감지 방법들
  methods:
    - type: "element_text"           # A매장 특화: parkName 요소 텍스트 확인
      selector: "#parkName"
      patterns: ["검색된 차량이 없습니다"]
      priority: 1
      
    - type: "text_pattern"           # 일반적인 텍스트 패턴 검색
      patterns: 
        - "검색된 차량이 없습니다"
        - "검색 결과가 없습니다"
        - "차량을 찾을 수 없습니다"
        - "등록된 차량이 없습니다"
      priority: 2
      
    - type: "locator_check"          # Playwright 로케이터 직접 사용
      locators:
        - 'text="검색된 차량이 없습니다"'
        - 'text="검색 결과가 없습니다"'
      priority: 3

  # 팝업 닫기 설정
  popup_close:
    selectors:
      - 'text=OK'
      - 'text=확인'
      - 'text=닫기'
      - 'button:has-text("OK")'
      - 'button:has-text("확인")'
      - '#popupOk'