# A매장 설정
store:
  id: "A"
  name: "동탄점"
  website_url: "http://members.iparking.co.kr/#!"
  
login:
  username: "dtctrit2704"
  password: "dtctrit2704"

# 쿠폰 설정 - 시간 독립적 설계 (4_discount_logic.mdc 기반)
coupons:
  FREE_COUPON:
    name: "30분할인권(무료)"
    type: "FREE"
    duration_minutes: 60
    priority: 0
  PAID_COUPON:
    name: "1시간할인권(유료)"
    type: "PAID"
    duration_minutes: 60
    priority: 1
  WEEKEND_COUPON:
    name: "1시간주말할인권(유료)"
    type: "WEEKEND"
    duration_minutes: 60
    priority: 2

# 할인 정책 - 시간 기반 (분 단위)
policy:
  weekday_target_minutes: 180  # 3시간
  weekend_target_minutes: 120  # 2시간

# 웹 셀렉터
selectors:
  # 로그인 관련
  login:
    username_input: "#id"
    password_input: "#password"
    login_button: "#login"
    car_number_input: "#carNumber"
  
  # 팝업 처리
  popups:
    intro_skip: "#skip"
    notice_cancel: "#popupCancel"
    after_login_home: "#gohome"
    after_login_start: "#start"
    popup_ok: "#popupOk"
  
  # 차량 검색
  search:
    car_number_input: "#carNumber"
    search_button: 'button[name="search"]'
    search_button_alt1: ".btn-search"
    search_button_alt2: 'button:has-text("검색")'
    next_button: "#next"
    next_button_alt: 'button:has-text("차량 선택")'
    park_name: "#parkName"
    no_result_text: 'text="검색된 차량이 없습니다"'
  
  # 쿠폰 관련
  coupons:
    product_list: "#productList"
    product_rows: "#productList tr"
    empty_message: "#productList td.empty"
    my_dc_list: "#myDcList"
    my_dc_rows: "#myDcList tr"
    all_dc_list: "#allDcList"
    all_dc_rows: "#allDcList tr"
    apply_button: 'button:has-text("적용")'
    apply_button_prefix: "#apply_"

# 차량 검색 실패 감지 설정
search_failure_detection:
  # 우선순위 순으로 시도할 감지 방법들
  methods:
    - type: "element_text"           # A매장 특화: parkName 요소 텍스트 확인
      selector: "#parkName"
      patterns: ["검색된 차량이 없습니다"]
      priority: 1
      
    - type: "text_pattern"           # 일반적인 텍스트 패턴 검색
      patterns: 
        - "검색된 차량이 없습니다"
        - "검색 결과가 없습니다"
        - "차량을 찾을 수 없습니다"
        - "등록된 차량이 없습니다"
      priority: 2
      
    - type: "locator_check"          # Playwright 로케이터 직접 사용
      locators:
        - 'text="검색된 차량이 없습니다"'
        - 'text="검색 결과가 없습니다"'
      priority: 3

  # 팝업 닫기 설정
  popup_close:
    selectors:
      - 'text=OK'
      - 'text=확인'
      - 'text=닫기'
      - 'button:has-text("OK")'
      - 'button:has-text("확인")'
      - '#popupOk'