# D매장 설정
store:
  id: "D"
  name: "D매장"
  website_url: "https://npdc-i.nicepark.co.kr"
  
login:
  username: "nad35101"
  password: "DLTNDUF!1"

# 쿠폰 설정 - 시간 독립적 설계 (B매장과 동일)
# D 매장 특징: 30분 단위 유료 쿠폰, 주말 전용 쿠폰 없음 (PAID로 fallback)
coupons:
  FREE_COUPON:
    name: "1시간 무료"
    type: "FREE"
    duration_minutes: 60
    priority: 0
  PAID_COUPON:
    name: "30분 유료"
    type: "PAID"
    duration_minutes: 30  # D매장 특징: 30분 단위
    priority: 1
  # WEEKEND 타입 쿠폰 없음 → 주말에도 PAID 타입 사용 (fallback)

# 할인 정책 - 시간 기반 (분 단위)
discount_policy:
  weekday:
    target_hours: 3
    max_coupons: 5
  weekend:
    target_hours: 2
    max_coupons: 3

# 웹 셀렉터 (실제 테스트로 확인된 값)
selectors:
  # 로그인 관련
  login:
    username_input: "#mf_wfm_body_ibx_empCd"
    password_input: "#mf_wfm_body_sct_password"
    login_button: "#mf_wfm_body_btn_login"
    car_number_input: "input[type=\"text\"]"
  
  # 팝업 처리 (비밀번호 만료 등)
  popups:
    password_expired_popup: "text=비밀번호가 만료되었습니다"
    notice_popup: ".modal"
    ok_button: "button:has-text('확인')"
    close_button: "button:has-text('닫기')"
    alert_ok: "button:has-text('OK')"
    login_success_indicator: "text=차량번호 뒤 4자리"
  
  # 차량 검색
  search:
    car_number_input: "#carNumber"
    search_button: "#searchBtn"
    no_result_message: 'text=검색된 차량이 없습니다'
    search_result_table: "#vehicleList"
  
  # 쿠폰 관련 (테스트로 검증된 셀렉터만 유지)
  coupons:
    # 보유 쿠폰 수량 파싱 (1단계에서 성공하는 핵심 셀렉터)
    hour_coupon_count: "#mf_wfm_body_gen_dcTkList_0_discountTkRemainCnt.w2textbox"
    min_coupon_count: "#mf_wfm_body_gen_dcTkList_1_discountTkRemainCnt.w2textbox"
    
    # 쿠폰 적용 버튼 (실제 동작 확인됨)
    apply_hour_button: "#mf_wfm_body_gen_dcTkList_0_discountTkGrp[role='button']"
    apply_min_button: "#mf_wfm_body_gen_dcTkList_1_discountTkGrp[role='button']"
    
    # 쿠폰 사용 이력 파싱 (YAML 기반으로 성공)
    history_30min_group: "#mf_wfm_body_gen_usedDcTkGrpList_0_discountTkGrp"
    history_1hour_group: "#mf_wfm_body_gen_usedDcTkGrpList_1_discountTkGrp"
    
  # 페이지 URL (추정)
  urls:
    login: "/login"
    main: "/main"
    coupon: "/coupon"

# 차량 검색 실패 감지 설정
search_failure_detection:
  # 우선순위 순으로 시도할 감지 방법들
  methods:
    - type: "popup_detection"        # D매장 특화: w2window 팝업 감지
      selectors:
        - ".w2window.w2window_restored.w2popup_window"
        - "div[id*='alert']"
        - "div[id*='mf_wfm_body_alert']"
        - ".w2popup_window textarea"
        - ".w2window .w2window_content"
      text_patterns: ["검색", "결과", "없음", "차량"]
      priority: 1
      
    - type: "text_pattern"           # 일반적인 텍스트 패턴
      patterns: 
        - "검색된 차량이 없습니다"
        - "검색 결과가 없습니다"
        - "차량을 찾을 수 없습니다"
        - "등록된 차량이 없습니다"
        - "조회 결과가 없습니다"
      priority: 2
      
    - type: "locator_check"          # Playwright 로케이터 직접 사용
      locators:
        - 'text="검색된 차량이 없습니다"'
        - 'text="검색 결과가 없습니다"'
      priority: 3

  # 팝업 닫기 설정 (D매장 w2window 특화)
  popup_close:
    selectors:
      - 'text=OK'
      - 'text=확인'
      - '.btn-confirm'
      - '.btn-close'
      - '.w2popup_window button'
      - '.w2window button[title="닫기"]'
      - '.w2window .w2window_close'
      - 'button:has-text("OK")'
      - 'button:has-text("확인")'