# E매장 설정 (동작하는 크롤러 기준으로 업데이트)
store:
  id: "E"
  name: "E매장"
  website_url: "https://a18120.pweb.kr/login"
  
login:
  username: "508"
  password: "1111"

# 쿠폰 설정 - 크롤러 코드에서 검증된 설정
# E 매장 특징: 1시간 단위 쿠폰만 지원 (무료/유료)
coupons:
  FREE_COUPON:
    name: "(무료) 1시간할인"
    type: "FREE"
    duration_minutes: 60
    priority: 0
    # 크롤러에서 사용: FREE_1HOUR 타입으로 매핑 (line 150-151)
  PAID_COUPON:
    name: "(유료) 1시간할인"
    type: "PAID"
    duration_minutes: 60
    priority: 1
    price: 300  # 크롤러에서 사용하는 가격 (line 264)
    # 크롤러에서 사용: PAID_1HOUR 타입으로 매핑 (line 152-153)

# 할인 정책 - 시간 기반 (분 단위)
discount_policy:
  weekday:
    target_hours: 3
    max_coupons: 5
  weekend:
    target_hours: 2
    max_coupons: 3

# 웹 셀렉터 (백업 크롤러에서 검증된 정확한 셀렉터)
selectors:
  # 로그인 관련 - 크롤러에서 검증된 셀렉터
  login:
    username_input: 'role=textbox[name="ID"]'  # line 34: get_by_role('textbox', name='ID')
    password_input: 'role=textbox[name="PASSWORD"]'  # line 35: get_by_role('textbox', name='PASSWORD')
    login_button: 'role=button[name="Submit"]'  # line 36: get_by_role('button', name='Submit')
    login_success_indicator: 'role=textbox[name="차량번호"]'  # line 44: 로그인 성공 확인용 차량번호 입력란
    search_state_checkbox: '#checkSaveID'  # line 215: 검색 상태 유지 체크박스
  
  # 팝업 처리 - 크롤러에서 검증된 셀렉터
  popups:
    notice_popup: 'text=안내'  # line 202: 안내 팝업
    ok_button: 'text=OK'  # line 203: 일반 OK 버튼  
    modal_ok_button: '.modal-buttons a:has-text("OK")'  # line 310: 쿠폰 적용 후 모달 팝업
  
  # 차량 검색 - 크롤러에서 검증된 셀렉터
  search:
    car_number_input: 'role=textbox[name="차량번호"]'  # line 72: get_by_role('textbox', name='차량번호')
    search_button: 'role=button[name="검색"]'  # line 76: get_by_role('button', name='검색')
    # 차량 검색 실패는 공통 check_no_vehicle_found 함수 사용 (line 86)
  
  # 쿠폰 관련 - 크롤러에서 검증된 셀렉터
  coupons:
    free_1hour_link: 'a:has-text("(무료) 1시간할인")'  # line 283: FREE_1HOUR 쿠폰 링크
    paid_1hour_link: 'a:has-text("(유료) 1시간할인")'  # line 283: PAID_1HOUR 쿠폰 링크  
    remaining_amount: 'text=남은잔여량'  # line 246: 남은잔여량 텍스트
    
    # 할인내역 테이블 셀렉터 - 크롤러에서 검증된 셀렉터
    # 공통 쿠폰 계산기와 할인내역 카운트에서 사용
    discount_selectors:
      - "tr.ev_dhx_skyblue"     # line 323: E 매장 기본 행 (짝수)
      - "tr.odd_dhx_skyblue"    # line 323: E 매장 홀수 행
      - "tr.rowselected"        # 선택된 행 (예비)
      - "#gridDtl tr"           # 할인내역 그리드 내 행 (예비)
      - ".gridbox tr"           # 그리드박스 내 행 (예비)
    
    # 쿠폰 이름 → 키 매핑 - 크롤러와 공통 쿠폰 계산기에서 사용
    coupon_key_mapping:
      "(무료) 1시간할인": "FREE_COUPON"  # line 193: YAML에서 로드하는 키
      "(유료) 1시간할인": "PAID_COUPON"  # line 193: YAML에서 로드하는 키
    
    # E 매장 테이블 데이터 구조 정보 - 공통 쿠폰 계산기용
    table_structure:
      description: "번호 | 할인값 | 등록자 | 등록일"
      coupon_name_cell_index: 1  # 쿠폰명이 있는 셀 인덱스 (0부터 시작)
      quantity_per_row: 1        # E 매장은 항상 행당 1개 쿠폰
      example: "1 | (유료) 1시간할인 | 508(관리자) | 2025-08-19 08:59:07.977"
  
  # 페이지 URL - E 매장 URL 구조
  urls:
    login: "/login"
    discount_registration: "/discount/registration"
    discount_status: "/state/doViewMst"
    discount_purchase: "/pay/doViewDscnt"

# 차량 검색 실패 감지 설정 - 크롤러에서는 공통 함수 사용
# 실제로는 check_no_vehicle_found 공통 함수 사용 (line 86)
search_failure_detection:
  # 공통 함수에서 사용하는 패턴들 (참고용)
  methods:
    - type: "text_pattern"           # E매장에서 나타나는 주요 패턴
      patterns: 
        - "검색 결과가 없습니다. 출차된 차량은 검색되지 않습니다."
        - "검색 결과가 없습니다"
        - "검색된 차량이 없습니다"
        - "차량을 찾을 수 없습니다"
        - "등록된 차량이 없습니다"
      priority: 1
      
    - type: "locator_check"          # Playwright 로케이터 직접 사용
      locators:
        - 'text="검색 결과가 없습니다. 출차된 차량은 검색되지 않습니다."'
        - 'text="검색 결과가 없습니다"'
        - 'text="검색된 차량이 없습니다"'
      priority: 2
      
    - type: "popup_detection"        # 팝업창 감지
      selectors:
        - ".modal"
        - ".popup"  
        - "div[role='dialog']"
      text_patterns: ["검색", "결과", "없음", "차량"]
      priority: 3

  # 팝업 닫기 설정
  popup_close:
    selectors:
      - 'text=OK'
      - 'text=확인'
      - 'text=닫기'
      - 'button:has-text("OK")'
      - 'button:has-text("확인")'
      - '.btn-close'

# 크롤러 특화 설정
crawler_specific:
  # 알림 관련 설정
  notifications:
    low_coupon_threshold: 50  # line 268: 쿠폰 부족 알림 임계값
    telegram_store_name: "[부천(e)매장]"  # line 237: 텔레그램 알림에 표시할 매장명
  
  # 쿠폰 적용 관련 설정
  coupon_application:
    wait_timeout: 500  # line 292: 쿠폰 적용 후 대기 시간(ms)
    table_update_max_retries: 10  # line 329: 테이블 업데이트 확인 최대 재시도 횟수
    table_update_interval: 500  # line 330: 테이블 업데이트 확인 간격(ms)